name: Events Demo 1
on: 
  pull_request:
    types: [opened, closed]
  workflow_dispatch:
  push:
    branches:
      - master  
      - 'dev-*' # Match any branch name starting with 'dev-'
      - 'feature/**' # Match any branch name starting with 'feature/ eg feature/abc, feature/xyz/axz'    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output Event Data
        run: echo "${{ toJson(github.event) }}"
      - name: Get code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install 
      - name: Run tests
        run: npm run test
      - name: Build code
        run: npm run build
      - name: Deploy project code 
        run: echo "Deploying code"     
